#!/bin/zsh
#

if sudo -v; then
    while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &
else
    echo "This script requires sudo privileges. Exiting."
    exit 1
fi

# Install Nix, unless it already exists

if ! command -v nix >/dev/null 2>&1; then
  echo "Installing Nix"
  sh <(curl -L https://nixos.org/nix/install)
else
  echo "Nix already installed, skipping"
fi

if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
  . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
fi

# Build and switch to Home Manager configuration

nix run home-manager -- init --switch
username=$(whoami)
home-manager switch --flake .#${username}

