version: '3'

tasks:
  default:
    cmds:
      - task --list

  switch:
    desc: Build using home-manager switch with dynamic macOS username
    vars:
      USERNAME:
        sh: whoami
    cmds:
      - home-manager switch --flake .#{{.USERNAME}}
